### ISSUE TITLE
Is this code still works for Umbraco 7.5.x?

### ISSUE THREAD

**Issue by bhaidar** [ViGiLnT/ApproveIt#3]
I started by adding the Section class only. Nothing shows in Umbraco backoffice. Has the method of adding a section changed since this code was written? Thanks

**Comment by ViGiLnT** [comment]
Hi @bhaidar ,

Nothing as changed, I believe. The section is not automatically added to your user in the backoffice, that's probably the problem. Go to your user's settings in the backoffice and check the "Approve It" section (or whatever you called it)

**Comment by MuirisOG** [comment]
I've been working through your 3 part tutorial and find them excellent. However, the trees are not working. I've noticed quite a few differences between your tutorial and the code here. In particular, you seem to be using a table called ""approveItChangeHistory". Can you explain where this is?
Many thanks.

**Comment by ViGiLnT** [comment]
Hi @MuirisOG,

The way of creating the trees (public class ApprovalTreeController : TreeController) is still the same. I recently gave a talk where I used those blog posts to recreate the ApproveIt plugin and was using Umbraco version 7.5.4 (or some version close to that) and everything still worked flawlessly.

The tutorial is completely different from the latest version on this repo, but you can still get the initial releases. You just need to use Git to get the commit you want.

After the 1.0 release I was building upon the plugin and started to create a custom table that would keep all versions that each content went by. This way, a content manager could check every change that was made (and by whom) and approve the version he liked the best.
It's still halfway done... You're welcome to pick it up! :)

Thanks for the feedback.

**Comment by MuirisOG** [comment]
I have completed the tutorial (many thanks - it is excellent), but struggled with `GetAll` function in `ApprovalApiController`, which I suspect is because our site has a very large number of nodes. (I tested a small section of the site instead, and got that working.) 

My next step is to see if I there is an alternative - maybe quicker - way to find all the unapproved pages, or perhaps a way to break the problem down, e.g. start with the main sections of the site.

**Comment by ViGiLnT** [comment]
The way I'm doing it now is by intercepting the "send to publish" event and storing the node waiting approval in that custom table "approveItChangeHistory". That way you don't need to traverse the all tree, you've got all content waiting approval in a custom table.

**Comment by MuirisOG** [comment]
Rather than capture events, I've created a view on the `cmsDocument` table for unpublished content, and using the method for displaying the contents of a table described in the Per Ploug's [UkFest-AngularJS-Demo](https://github.com/perploug/UkFest-AngularJS-Demo), and code from your tutorial, I've managed to get something for the Tree Controller that returns pretty quick and useful results in the custom backoffice section.

**Comment by ViGiLnT** [comment]
Nice. Looks like a good workaround! You just have to hope Umbraco doesn't update the cmsDocument table structure. ;)
