### ISSUE TITLE
Cant install via zip file

### ISSUE THREAD

**Issue by GavinH32** [ViGiLnT/ApproveIt#4]
I'm using umbraco 7.5.4 and the file wont install via zip. Just does nothing. Can you suggest a work around or a solution?

I tried the latest version as well (7.6.3) and still no luck.

**Comment by ViGiLnT** [comment]
Hi @GavinH32 ,

I've just tried it in Umbraco 7.5.4 and everything went smoothly. Did it show any error during installation?

In order for you to have access to the new section "Approve It", you must explicitly give permissions to your user for it. You can do that by going to the users section in the Umbraco backoffice, selecting your user, and ticking the "Approve It" checkbox. You can see this in the attached screenshot:

![approveit](https://user-images.githubusercontent.com/92072/27690101-460ba3e2-5cd8-11e7-8ef1-9bb9777daa79.png)

After ticking that checkbox you must refresh your browser in order for the Approve It section to actually show up.

**Comment by ViGiLnT** [comment]
Just tried it in Umbraco 7.6.3 and it also works.

**Comment by GavinH32** [comment]
I have managed to get the one without the page preview on and that works great but the v1.2 you never finished was the one I was on about.

**Comment by ViGiLnT** [comment]
Hi @GavinH32 

Sorry for the late reply. I've just tried the unreleased version with Umbraco 7.6.x and it's not working. The reason being that since version 7.6 the content node ids are no longer integers but guids.

I tried to install it in Umbraco 7.5.12 and the plugin is working:

![image](https://user-images.githubusercontent.com/92072/27825493-a451fc58-60a7-11e7-9907-9c0b24a08a43.png)

There is a problem with the process of creating translations during package installation but that's it. Need to investigate further.

I'll attach the zip file with the plugin in this comment.
[ApproveIt.v1.0.1.zip](https://github.com/ViGiLnT/ApproveIt/files/1121662/ApproveIt.v1.0.1.zip)

**Comment by GavinH32** [comment]
Well the 1.0.1 version installs and works fine though I think the preview is encountering a problem with detecting the changes with the datatypes I have, though you did explain that in you post on our.umbraco.org. I think our developers could continue to work on this and maybe improve the plugin but at least we have something that works to a point.

If you can let know when the plugin is working in 7.6.x that would be great.

Thank you for looking at this.

**Comment by GavinH32** [comment]
I'm also trying to reverse feature that is highlighting the text so only changes have a background colour. Any suggestions where or how I could do this?

**Comment by ViGiLnT** [comment]
@GavinH32 we used this javascript plugin: https://github.com/picapica-org/jQuery.picadiff

All javascript we used is available here: https://github.com/ViGiLnT/ApproveIt/tree/master/ApproveIt/App_Plugins/ApproveIt/Scripts/pickadiff

All css is here: https://github.com/ViGiLnT/ApproveIt/tree/master/ApproveIt/App_Plugins/ApproveIt/Content/pickadiff
